### ISSUE TITLE
_sha3' has no attribute 'sha3

### ISSUE THREAD

**Issue by maedat** [piroyon/cat_color_detect#1]
Thank you for good tools. 
I got below errors on excite_image_collector.py.
Do you have any idea to resolve this problem? 

https://imagesearch.excite.co.jp/?q=Hypselodoris%2Bfestiva&page=1
Traceback (most recent call last):
  File "excite_image_collector.py", line 91, in <module>
    fetch_and_save_img(query)
  File "excite_image_collector.py", line 54, in fetch_and_save_img
    hashed_name = hashlib.sha3_256(encode_url).hexdigest()
  File "/usr/local/lib/python3.7/site-packages/sha3/__init__.py", line 97, in sha3_256
    return SHA3256(s)
  File "/usr/local/lib/python3.7/site-packages/sha3/__init__.py", line 30, in __init__
    self._s = _sha3.sha3()
AttributeError: module '_sha3' has no attribute 'sha3'

My environment;
Mac OS Mojave 10.14.4
Python 3.7.3
pysha3 1.0.2

**Comment by piroyon** [comment]
It uses "pysha3" which conflicts "sha3" package.
Please uninstall sha3 and install pysha3.

**Comment by maedat** [comment]
Thanks a lot! It worked well with uninstalling of "sha3".
